wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 30
weight_decay:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701645986.632952
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
