wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 10
weight_decay:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699309498.079541
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
